# Site settings
course_title: "CS290: Seminar on Effective Research Practices & Academic Culture"
course_name: "CS290: Seminar on Effective Research Practices & Academic Culture"
course_semester: "Fall 2023 - Spring 2024"

baseurl: "/" # the subpath of your site, e.g. /blog/
url: "https://harvard-cs290.github.io" # the base hostname & protocol for your site

schoolname: "Harvard University"
schoolurl: 

address: |
    John A. Paulson School of Engineering and Applied Sciences
    Harvard University
    Science and Engineering Complex
    150 Western Ave, Boston, MA 02134

# Set your Google Analytics tracking ID (set up yours at http://www.google.com/analytics/)
# google_analytics: UA-XXXXXXXX-X

### Do not change the followings unless you know what you are doing ###

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']
exclude: ['develop']

dateformat: "%m/%d/%Y"

future: true
collections:
    events:
        output: true
    lectures:
        output: false
    assignments:
        output: true
    announcements:
        output: false


defaults:
  - scope:
      path: ""
      type: "assignments"
    values:
      layout: "assignment"
